x-strapi-base: &strapi_base
  restart: unless-stopped
  working_dir: /srv/app

services:

  typesense:
    image: typesense/typesense:0.25.2
    container_name: typesense
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:-dev_typesense_key}
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_ENABLE_CORS: "true"
    volumes:
      - typesense_data:/data
    profiles: ["fat", "uat"]

volumes:
  typesense_data:
